apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekc-api
spec:
  template:
    spec:
      containers:
        - name: api
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekc-worker
spec:
  template:
    spec:
      containers:
        - name: worker
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekc-guardrails
spec:
  template:
    spec:
      containers:
        - name: guardrails
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 2Gi
