apiVersion: v1
kind: Service
metadata:
  name: ekc-guardrails
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8001"
    prometheus.io/path: "/metrics"
spec:
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: http
  selector:
    app: ekc-guardrails
  type: ClusterIP
