apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekc-jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ekc-jaeger
  template:
    metadata:
      labels:
        app: ekc-jaeger
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1883
        runAsGroup: 1883
        fsGroup: 1883
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
          ports:
            - containerPort: 16686
              name: web
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 16686
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 16686
            initialDelaySeconds: 10
            periodSeconds: 10
