apiVersion: v1
kind: Service
metadata:
  name: ekc-qdrant
spec:
  ports:
    - port: 6333
      targetPort: 6333
      name: http
    - port: 6334
      targetPort: 6334
      name: grpc
  selector:
    app: ekc-qdrant
  clusterIP: None
