apiVersion: v1
kind: Secret
metadata:
  name: ekc-secrets
type: Opaque
data:
  GEMINI_API_KEY: "QUl6YVN5RHBuQkd1V0JQN1RTbk5HSlBqemp6RHBxb2FJbHFOaU9Z"
  JWT_SECRET_KEY: "cmVwbGFjZS13aXRoLWEtc2VjdXJlLXNlY3JldC1rZXk="
  POSTGRES_DSN: "cG9zdGdyZXNxbDovL2tub3dsZWRnZV9jb3BpbG90X3VzZXI6VSUtNlNOUF9JTyVJeHpSPiloYTJZcmhlQDEwLjYyLjAuMzo1NDMyL2tub3dsZWRnZV9jb3BpbG90"
  DEFAULT_API_KEY: "ZWtjX2Rldl9rZXlfMTIzNDU="
