import json
import logging
from urllib.parse import urlencode

from fastapi import Request, Response
from fastapi.responses import JSONResponse
from starlette.middleware.base import BaseHTTPMiddleware

from packages.safety import SafetyGuardrailsClient, verify_citations_bounds

logger = logging.getLogger("apps.api.middleware.safety")


class SafetyGuardrailsMiddleware(BaseHTTPMiddleware):
    """FastAPI Middleware to enforce robust input/output security and PII masking.

    1. Intercepts queries at '/ask' and '/search' endpoints.
    2. Invokes NeMo Guardrails microservice (with local regex fallback) for input safety checks.
    3. Blocks unsafe/off-topic requests with standard refusal error schemas.
    4. Automatically intercepts output generated by '/ask' and evaluates grounding context.
    5. Replaces ungrounded answers/hallucinations with safety fallbacks.
    """

    def __init__(self, app, service_url: str | None = None):
        super().__init__(app)
        self.safety_client = SafetyGuardrailsClient(service_url=service_url)

    async def dispatch(self, request: Request, call_next):
        path = request.url.path

        # Only validate user-facing query endpoints
        if path not in ["/ask", "/search"]:
            return await call_next(request)

        # Input Safety Validation
        query = request.query_params.get("q", "").strip()
        if not query:
            return await call_next(request)

        logger.info(f"[SafetyMiddleware] Intercepted input query: {query}")

        input_result = await self.safety_client.validate_input(query)

        # Block if unsafe or off-topic
        if not input_result.get("is_safe", True) or input_result.get("is_off_topic", False):
            refusal = (
                input_result.get("refusal_message")
                or "I cannot fulfill this request as it violates enterprise security policies."
            )
            logger.warning(
                f"[SafetyMiddleware] Blocked unsafe/off-topic input query: {query}."
                f"Reason: {refusal}"
            )
            return JSONResponse(
                status_code=400,
                content={"detail": refusal, "error_code": "SAFETY_POLICY_VIOLATION", "safe": False},
            )

        # PII Masking
        filtered_query = input_result.get("filtered_query", query)
        if filtered_query != query:
            logger.info(
                f"[SafetyMiddleware] Masked PII in input query. "
                f"Original: {query} -> Filtered: {filtered_query}"
            )

            scope = request.scope
            params = []
            for k, v in request.query_params.multi_items():
                if k == "q":
                    params.append((k, filtered_query))
                else:
                    params.append((k, v))
            scope["query_string"] = urlencode(params).encode("utf-8")

        response = await call_next(request)

        if path == "/ask" and response.status_code == 200:
            try:
                body_bytes = b""
                async for chunk in response.body_iterator:
                    body_bytes += chunk

                try:
                    response_json = json.loads(body_bytes.decode("utf-8"))
                    answer = response_json.get("answer", "")
                    citations = response_json.get("citations", [])

                    # Context chunks are in the citation snippets
                    context_chunks = [
                        cit.get("snippet", "") for cit in citations if cit.get("snippet")
                    ]

                    if answer:
                        # Zero-latency local citation bounds check
                        if not verify_citations_bounds(answer, len(citations)):
                            logger.warning(
                                "[SafetyMiddleware] Citation out-of-bounds detected locally! "
                                "Blocking response."
                            )
                            refusal = (
                                "I'm sorry, but I cannot verify this information with internal "
                                "sources. Please try rephrasing your query."
                            )
                            response_json["answer"] = refusal
                            response_json["citations"] = []
                            body_bytes = json.dumps(response_json).encode("utf-8")
                        elif context_chunks:
                            # Call Guardrails microservice for semantic grounding verification
                            logger.info(
                                "[SafetyMiddleware] Validating grounding for generated answer."
                            )
                            output_result = await self.safety_client.validate_output(
                                query=filtered_query, answer=answer, context=context_chunks
                            )

                            # If not grounded, block or replace response
                            if not output_result.get("is_grounded", True):
                                refusal = output_result.get("refusal_message") or (
                                    "I'm sorry, but I cannot verify this information with "
                                    "internal sources. Please try rephrasing your query."
                                )
                                logger.warning(
                                    "[SafetyMiddleware] Hallucination detected! Answer was "
                                    "ungrounded. Replacing with refusal."
                                )
                                response_json["answer"] = refusal
                                response_json["citations"] = []
                                body_bytes = json.dumps(response_json).encode("utf-8")
                except json.JSONDecodeError:
                    pass  # Non-JSON or malformed output, let it pass

                return Response(
                    content=body_bytes,
                    status_code=response.status_code,
                    headers=dict(response.headers),
                    media_type=response.media_type,
                )
            except Exception as out_err:
                logger.error(
                    f"[SafetyMiddleware] Error in output grounding interceptor: {out_err}",
                    exc_info=True,
                )

        return response
