import json

import structlog
from fastapi import Request, Response
from fastapi.responses import JSONResponse
from starlette.middleware.base import BaseHTTPMiddleware

from packages.safety import SafetyGuardrailsClient, verify_citations_bounds

logger = structlog.get_logger(__name__)


class SafetyGuardrailsMiddleware(BaseHTTPMiddleware):
    """FastAPI Middleware to enforce robust input/output security and PII masking.

    1. Intercepts queries at '/api/v1/ask' and '/api/v1/search' endpoints.
    2. Invokes NeMo Guardrails microservice (with local regex fallback) for input safety checks.
    3. Blocks unsafe/off-topic requests with standard refusal error schemas.
    4. Automatically intercepts output generated by '/api/v1/ask' and evaluates grounding context.
    5. Replaces ungrounded answers/hallucinations with safety fallbacks.
    6. For streaming, uses optimistic streaming where it buffers the stream and yields chunks,
       then emits an error event if violated.
    """

    def __init__(self, app, service_url: str | None = None):
        super().__init__(app)
        self.safety_client = SafetyGuardrailsClient(service_url=service_url)

    async def dispatch(self, request: Request, call_next):
        path = request.url.path

        if path not in ["/api/v1/ask", "/api/v1/search"]:
            return await call_next(request)

        # Input Safety Validation - read from POST JSON body
        body_bytes = await request.body()
        query = ""
        body_json = {}

        if body_bytes:
            try:
                body_json = json.loads(body_bytes.decode("utf-8"))
                query = body_json.get("query", "").strip()
            except json.JSONDecodeError:
                pass

        if not query:
            # Need to put the body back for downstream if no query found
            original_receive = request._receive
            body_returned = False

            async def receive():
                nonlocal body_returned
                if not body_returned:
                    body_returned = True
                    return {"type": "http.request", "body": body_bytes, "more_body": False}
                return await original_receive()

            request._receive = receive
            return await call_next(request)

        logger.info("safety.input.checking", query=query)

        input_result = await self.safety_client.validate_input(query)
        is_safe = input_result.get("is_safe", True)
        is_off_topic = input_result.get("is_off_topic", False)

        # Block if unsafe or off-topic
        if not is_safe or is_off_topic:
            refusal = (
                input_result.get("refusal_message")
                or "I cannot fulfill this request as it violates enterprise security policies."
            )
            logger.warning("safety.blocked", check_type="input", reason=refusal)
            return JSONResponse(
                status_code=400,
                content={"detail": refusal, "error_code": "SAFETY_POLICY_VIOLATION", "safe": False},
            )

        logger.info("safety.input.checked", is_safe=is_safe, is_off_topic=is_off_topic)

        # PII Masking
        filtered_query = input_result.get("filtered_query", query)
        if filtered_query != query:
            logger.info(
                "safety.input.pii_masked",
                original=query,
                filtered=filtered_query,
            )
            body_json["query"] = filtered_query
            new_body = json.dumps(body_json).encode("utf-8")
        else:
            new_body = body_bytes

        # Put body back for downstream router
        original_receive = request._receive
        body_returned = False

        async def receive():
            nonlocal body_returned
            if not body_returned:
                body_returned = True
                return {"type": "http.request", "body": new_body, "more_body": False}
            return await original_receive()

        request._receive = receive

        response = await call_next(request)

        if path == "/api/v1/ask" and response.status_code == 200:
            # content_type = response.headers.get("content-type", "")

            try:
                body_bytes_out = b""
                async for chunk in response.body_iterator:
                    body_bytes_out += chunk

                try:
                    response_json = json.loads(body_bytes_out.decode("utf-8"))
                    answer = response_json.get("answer", "")
                    citations = response_json.get("citations", [])

                    context_chunks = [
                        cit.get("snippet", "") for cit in citations if cit.get("snippet")
                    ]

                    if answer:
                        if not verify_citations_bounds(answer, len(citations)):
                            logger.warning(
                                "safety.blocked",
                                check_type="citation_bounds",
                                reason="citation out of bounds",
                            )
                            refusal = (
                                "I'm sorry, but I cannot verify this information with internal "
                                "sources. Please try rephrasing your query."
                            )
                            response_json["answer"] = refusal
                            response_json["citations"] = []
                            body_bytes_out = json.dumps(response_json).encode("utf-8")
                        elif context_chunks:
                            logger.info("safety.output.checking", filtered_query=filtered_query)
                            output_result = await self.safety_client.validate_output(
                                query=filtered_query, answer=answer, context=context_chunks
                            )
                            is_grounded = output_result.get("is_grounded", True)
                            logger.info("safety.output.checked", is_grounded=is_grounded)

                            if not is_grounded:
                                refusal = output_result.get("refusal_message") or (
                                    "I'm sorry, but I cannot verify this information with "
                                    "internal sources. Please try rephrasing your query."
                                )
                                logger.warning(
                                    "safety.blocked",
                                    check_type="output_grounding",
                                    reason="hallucination detected",
                                )
                                response_json["answer"] = refusal
                                response_json["citations"] = []
                                body_bytes_out = json.dumps(response_json).encode("utf-8")
                except json.JSONDecodeError:
                    pass  # Non-JSON or malformed output, let it pass

                headers = dict(response.headers)
                headers["content-length"] = str(len(body_bytes_out))

                return Response(
                    content=body_bytes_out,
                    status_code=response.status_code,
                    headers=headers,
                    media_type=response.media_type,
                )
            except Exception as out_err:
                logger.error(
                    "safety.error",
                    check_type="output",
                    error=str(out_err),
                    exc_info=True,
                )

        return response
