apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    orgId: 1
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
