apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ekc-prod
namePrefix: prod-

resources:
  - ../../base
  - pdb.yaml

patches:
  - path: patches/replicas.yaml
  - path: patches/resources.yaml
  - path: patches/configmap.yaml
  - target:
      kind: Namespace
      name: ekc
    patch: |-
      - op: replace
        path: /metadata/name
        value: ekc-prod

images:
  - name: ekc-api
    newName: us-central1-docker.pkg.dev/clean-carrier-500104-i0/ekc-images/api
    newTag: stable
  - name: ekc-worker
    newName: us-central1-docker.pkg.dev/clean-carrier-500104-i0/ekc-images/worker
    newTag: stable
  - name: ekc-guardrails
    newName: us-central1-docker.pkg.dev/clean-carrier-500104-i0/ekc-images/guardrails
    newTag: stable
  - name: ekc-frontend
    newName: us-central1-docker.pkg.dev/clean-carrier-500104-i0/ekc-images/frontend
    newTag: stable
